clothing_store/clothing_store/urls.py
from django.contrib import admin
from django.urls import path, include
from clothing_store import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothing_store/shop/urls.py
from django.urls import path

from shop.views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('registration/', RegistrationPage.as_view(), name='registration'),
    path('logout/', logout_user, name='logout'),
    path('account/', AccountPage.as_view(), name='account'),
    path('category/<slug:category_slug>/', CategoryPage.as_view(), name='category'),
    path('item/<slug:item_slug>/', ItemPage.as_view(), name='item'),
    path('cart_add/<int:item_id>/', cart_add, name='cart_add'),
    path('cart_remove/<slug:item_code>/', cart_remove, name='cart_remove'),
    path('place_on_order', place_on_order_page, name='place_on_order'),
    path('payment', payment_page, name='payment'),
    path('change_currency/', change_currency, name='change_currency'),
    path('my_orders/', my_orders, name='my_orders'),
    path('my_orders/<slug:context>', my_orders, name='my_orders'),
    path('chart_page', chart_page, name='chart_page'),
    path('export/products/', export_products_to_csv, name='export_products_to_csv'),
    path('export/users/', export_users_to_csv, name='export_users_to_csv'),
]

clothing_store/shop/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.sites import requests
from django.db import models
from django.urls import reverse
from django.conf import settings
import requests
from bs4 import BeautifulSoup

from clothing_store import settings



class Currency(models.Model):
    name = models.CharField(verbose_name='Название валюты', max_length=255)
    conversion_rate = models.DecimalField(verbose_name='Коэффициент конвертации', max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):

    def create_user(self, username, email, password, first_name='', last_name='', father_name='', phone='',
                    country='', region='', city='', address='', post_index=''):
        if not email:
            raise ValueError('У пользователя должен быть E-mail адрес')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password,
            father_name=father_name,
            phone=phone,
            country=country,
            region=region,
            city=city,
            address=address,
            post_index=post_index,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, first_name='', last_name='', father_name='', phone='',
                         country='', region='', city='', address='', post_index=''):
        user = self.create_user(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password,
            father_name=father_name,
            phone=phone,
            country=country,
            region=region,
            city=city,
            address=address,
            post_index=post_index,
        )

        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(verbose_name='Имя пользователя', max_length=63, unique=True)
    first_name = models.CharField(verbose_name='Имя', max_length=255, blank=True)
    last_name = models.CharField(verbose_name='Фамилия', max_length=255, blank=True)
    father_name = models.CharField(verbose_name='ОТЧЕСТВО', max_length=255, blank=True)
    phone = models.CharField(verbose_name='ТЕЛЕФОН', max_length=20, blank=True)
    country = models.CharField(verbose_name='СТРАНА', max_length=255, blank=True)
    region = models.CharField(verbose_name='КРАЙ/ОБЛАСТЬ/РЕГИОН', max_length=255, blank=True)
    city = models.CharField(verbose_name='ГОРОД', max_length=255, blank=True)
    address = models.CharField(verbose_name='АДРЕС', max_length=255, blank=True)
    post_index = models.CharField(verbose_name='ИНДЕКС', max_length=255, blank=True)
    email = models.EmailField(verbose_name='ЭЛ. ПОЧТА', max_length=255, unique=True)
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    is_staff = models.BooleanField(verbose_name='Сотрудник', default=False)
    is_superuser = models.BooleanField(verbose_name='Администратор', default=False)
    date_joined = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)
    currency = models.CharField(max_length=3, default='RUB')
    temporary_currency = models.CharField(max_length=3, default='RUB', blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_stuff(self):
        return self.is_staff

    def save(self, *args, **kwargs):
        super().save()

    def get_absolute_url(self):
        return reverse('account', kwargs={'username': self.username})


class Category(models.Model):
    """Модель категории"""

    name = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(db_index=True, unique=True, verbose_name='URL')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class Item(models.Model):
    """Модель товара"""

    name = models.CharField(max_length=255, verbose_name='Название')
    main_photo = models.ImageField(upload_to="images/photo/", verbose_name='Главное фото')
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.PROTECT)
    slug = models.SlugField(db_index=True, unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание')
    price = models.BigIntegerField(verbose_name='Цена в рублях')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления товара')
    is_in_stock = models.BooleanField(default=False, verbose_name='Есть в наличии')
    conversion_rates = {}

    def convert_price(self, currency):
        if currency not in self.conversion_rates:
            self.update_conversion_rates()
        conversion_rate = self.conversion_rates[currency]
        converted_price = round(self.price * conversion_rate, 2)
        return converted_price

    def update_conversion_rates(self):
        url = 'https://v6.exchangerate-api.com/v6/74942ad6620965e43cb2afd8/latest/RUB'

        response = requests.get(url)
        data = dict(response.json())

        conversion_rates = data['conversion_rates']

        self.conversion_rates.update(conversion_rates)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'{self.pk}_{self.name}'

    def get_absolute_url(self):
        return reverse('item', kwargs={'item_slug': self.slug})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id']


class Order(models.Model):
    """Модель заказа"""

    user_id = models.ForeignKey(User, verbose_name='Аккаунт заказчика', on_delete=models.PROTECT)
    first_name = models.TextField(verbose_name='Имя')
    last_name = models.TextField(verbose_name='Фамилия')
    father_name = models.TextField(verbose_name='Отчество')
    phone = models.TextField(verbose_name='Телефон')
    email = models.TextField(verbose_name='ЭЛ. ПОЧТА')
    country = models.TextField(verbose_name='Страна')
    city = models.TextField(verbose_name='Город')
    region = models.TextField(verbose_name='Край / Область / Регион')
    address = models.TextField(verbose_name='Адрес')
    mail_index = models.TextField(verbose_name='Почтовый индекс')
    note = models.TextField(verbose_name='Примечание')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')
    date_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления товара')
    status = models.TextField(default="Не оплачен", verbose_name="Статус")
    total_price = models.PositiveIntegerField(verbose_name="Сумма заказа",default=0)
    payment_code = models.TextField(verbose_name='Ключ оплаты')

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return str(self.user_id) + str(self.status)



class LinkinOrdersAndItems(models.Model):

    order = models.ForeignKey(Order, verbose_name="Заказ", on_delete=models.PROTECT)
    item = models.ForeignKey(Item, verbose_name="Товар", on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(verbose_name="Количество")
    size = models.TextField(verbose_name="Размер")


    class Meta:
        verbose_name = "Связь заказов с товарами"
        verbose_name_plural = "Связи заказов с товарами"

    def __str__(self):
        return f'{self.pk}_{self.order}_{self.item}'



class AdditionalImageItem(models.Model):
    """Модель изображения товара"""

    path = models.ImageField(upload_to="images/photo/", verbose_name='Фото')
    item = models.ForeignKey(Item, default=None, on_delete=models.CASCADE, verbose_name='Товар', related_name='add_images')

    class Meta:
        verbose_name = 'Дополнительное изображение товара'
        verbose_name_plural = 'Дополнительные изображения товара'

    def __str__(self):
        return self.item.name + ' _ADD_Image'

class OrderData:
    """Модель данных заказа"""

    def __init__(self, request, recreate=False):
        self.session = request.session
        order_data = self.session.get(settings.USERDATA_SESSION_ID)
        if recreate:
            order_data = self.session[settings.USERDATA_SESSION_ID] = dict(request.GET)
        self.order_data = order_data

    def save(self):
        self.session[settings.USERDATA_SESSION_ID] = self.order_data
        self.session.modified = True

    def __str__(self):
        return str(self.session.get(settings.USERDATA_SESSION_ID))

    def get_dict_of_data(self):
        return self.session.get(settings.USERDATA_SESSION_ID)

class Cart(object):
    """Модель корзины"""

    def __init__(self, request):
        """
        Инициализируем корзину
        """
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

    def add(self, item, size, quantity=1, update_quantity=False):
        """
        Добавить продукт в корзину или обновить его количество.
        """
        item_code = f"{item.id}_{size}"
        if item_code not in self.cart:
            self.cart[item_code] = {'quantity': 0,
                                  'price': str(item.price),

clothing_store/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from shop.models import User


class RegisterUserForm(UserCreationForm):
    """Форма регистрации пользователя"""

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={
        'class': 'modal__signup-classic-field-input',
        'id': 'signup-username',
        'maxlength': "255",
        'autocomplete': 'username',
        'required': True,
    }))

    email = forms.CharField(label='Эл.почта', widget=forms.EmailInput(attrs={
        'class': 'modal__signup-classic-field-input',
        'id': 'signup-email',
        'maxlength': "255",
        'autocomplete': 'email',
        'required': True,
    }))

    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'modal__signup-classic-field-input',
        'id': 'signup-password',
        'maxlength': "255",
        'autocomplete': 'new-password',
        'required': True,
    }))

    password2 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'modal__signup-classic-field-input',
        'id': 'signup-confirmation',
        'maxlength': "255",
        'autocomplete': 'new-password',
        'required': True,
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    """Форма авторизации пользователя"""


    username = forms.EmailField(label='ЭЛ.ПОЧТА', widget=forms.EmailInput(attrs={
            'class': 'modal__signin-classic-field-input',
            'id': 'signin-email',
            'maxlength': '255',
            'autocomplete': 'email',
            'required': True,
        }))

    password = forms.CharField(label='ПАРОЛЬ', widget=forms.PasswordInput(attrs={
        'class': 'modal__signin-classic-field-input',
        'id': 'signin-password',
        'maxlength': '255',
        'autocomplete': 'current-password',
        'required': True,
    }))


    class Meta:
        model = User


class MainUserDataForm(forms.Form):

    first_name = forms.CharField(label='ИМЯ', widget=forms.TextInput(attrs={
        'name': 'first_name',
        'class': 'account__details-personal-data-item-input',
        'maxlength': "30"
    }))

    last_name = forms.CharField(label='ФАМИЛИЯ', widget=forms.TextInput(attrs={
        'name': 'last_name',
        'class': 'account__details-personal-data-item-input',
        'maxlength': "30"
    }))

    father_name = forms.CharField(label='ОТЧЕСТВО', widget=forms.TextInput(attrs={
        'name': 'middle_name',
        'class': 'account__details-personal-data-item-input',
        'maxlength': "30"
    }))

    phone = forms.CharField(label='ТЕЛЕФОН', widget=forms.TextInput(attrs={
        'name': 'phone',
        'class': 'account__details-personal-data-item-input'
    }))

    email = forms.EmailField(label='ЭЛ.ПОЧТА', widget=forms.TextInput(attrs={
        'name': 'email',
        'class': 'account__details-personal-data-item-input unchangable'
    }))
    country = forms.CharField(label='СТРАНА', widget=forms.TextInput(attrs={
        'name': 'country',
        'class': 'account__details-delivery-item-input',
        'maxlength': "30"
    }))

    city = forms.CharField(label='ГОРОД', widget=forms.TextInput(attrs={
        'name': 'city',
        'class': 'account__details-delivery-item-input',
        'maxlength': "30"
    }))

    address = forms.CharField(label='АДРЕС', widget=forms.TextInput(attrs={
        'name': 'address',
        'class': 'account__details-delivery-item-input',
        'maxlength': "30"
    }))

    post_index = forms.CharField(label='ПОЧТОВЫЙ ИНДЕКС', widget=forms.TextInput(attrs={
        'name': 'post_index',
        'class': 'account__details-delivery-item-input',
        'maxlength': "30"
    }))

    region = forms.EmailField(label='РЕГИОН', widget=forms.TextInput(attrs={
        'name': 'region',
        'class': 'account__details-delivery-item-input',
        'maxlength': "30"
    }))

    password = forms.CharField(label='Новый Пароль', widget=forms.PasswordInput(attrs={
        'class': 'account__details-personal-data-item-input1',
        'name': 'password',
        'maxlength': "255"
    }), required=False)

    password_confirmation = forms.CharField(label='Повторите Пароль', widget=forms.PasswordInput(attrs={
        'class': 'account__details-personal-data-item-input1',
        'name': 'password_confirmation',
        'maxlength': "255"
    }), required=False)


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'father_name', 'phone', 'email', 'country', 'city',
                  'address', 'post_index', 'region', 'password', 'password_confirmation')

clothing_store/shop/templates/shop/beta сайт.html
<!DOCTYPE html>
<html lang="ru" translate="no">
    <head>
        <meta charset = "UTF-8">
        <meta http-equiv = "X-UA-Compatible" content = "IE=edge">
        <meta name = "viewport" content = "width = device - width, initial-scale = 1.0">
        <title>Продажный сайт</title>
        <link rel="icon" href="/ "/>

        <!-- Bootstrap reboot (для сброса стилей) -->
        <link rel="stylesheet" href="https://github.com/white0nyx/clothing_shop/blob/newbeta/clothing_store/shop/static/shop/bootstrap-reboot.min.css">

        <!-- Bootstrap сетка -->
        <link rel="stylesheet" href="https://github.com/white0nyx/clothing_shop/blob/newbeta/clothing_store/shop/static/shop/bootstrap-grid.min.css">

        <!-- Шрифты с Google Fonts -->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

        <!-- Стили сайта -->
        <link rel="stylesheet" href="https://github.com/white0nyx/clothing_shop/blob/newbeta/clothing_store/shop/static/shop/style0.css">
    </head>
    <body>
        <nav class = "header">
            <div class = "container1">
                <a href = "#" class = "header-brand">Логотип</a>
                <div class = "header-first">
                    <a href = "#" class = "button1">Вход</a>
                    <a href = "#" class = "button1">Регистрация</a>
                </div>
            </div>
            <div class = "container2">
                <div class = "header-second">
                    <ul class = "header-menu">
                        <li><a href = "#">Футболки</a></li>
                        <li><a href = "#">Свитшоты/худи</a></li>
                        <li><a href = "#">Штаны/шорты</a></li>
                        <li><a href = "#">Шапки</a></li>
                        <li><a href = "#">Рюкзаки/сумки</a></li>
                        <li><a href = "#">FAQ</a></li>
                        <li><a href = "#">Ваш заказ</a></li>
                    </ul>
                </div>
                <div class="header-buttons">
                    <a href = "#" class = "button2">РУС</a>
                    <a href = "#" class = "button2">РУБ</a>
                    <a href = "#" class = "button2">Корзина</a>
                </div>
            </div>
        </nav>
        <div class = "category-list">
            <div class="category-list-content">
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.netttps://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
            </div>
            <div class="category-list-content">
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
                <a class="category-product" href="#">
                    <div class="category-product-cover">
                        <div class = "picture">
                            <img src = "https://i10.fotocdn.net/s129/b6dac277ecd88eb7/public_pin_l/2923996590.jpg" width = "362px" height = "379px" alt = "Картинка с котиком">
                        </div>
                        <div class="category-product-blackout"></div>
                        <div class="price category-product-price">
                            <div class="price-current">
                                <span>Цена котика</span>
                            </div>
                        </div>
                    </div>
                    <button type="button" class="category-product-name">
                        <span>Название котика</span>
                    </button>
                </a>
            </div>
        </div>
    </body>
</html>

clothing_store/shop/templates/shop/categories_in_footer.html
<div class="before-row">
    <div class="footer-col1">
        <ul>
            {% for cat in categories %}
            {% if category_selected == cat.id %}
            {{cat.id}}
            {{category_selected}}
            <li class="footer-menu-item">{{ cat.name }}</li>
            {% else %}
            <li class="footer-menu-item"><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

<!--<div class="before-row">-->
<!--    <div class="footer-col1">-->
<!--        <ul>-->
<!--            <li class="footer-menu-item"><a href="http://127.0.0.1:8000/category/t-shirts/#">Футболки</a></li>-->
<!--            <li class="footer-menu-item"><a href="http://127.0.0.1:8000/category/sweatshirts/">Свитшоты/худи</a>-->
<!--            </li>-->
<!--            <li class="footer-menu-item"><a href="http://127.0.0.1:8000/category/pants-shorts/">Штаны/шорты</a>-->
<!--            </li>-->
<!--            <li class="footer-menu-item"><a href="http://127.0.0.1:8000/category/hats/">Шапки</a></li>-->
<!--            <li class="footer-menu-item"><a href="http://127.0.0.1:8000/category/bags/">Рюкзаки/сумки</a></li>-->
<!--        </ul>-->
<!--    </div>-->
<!--</div>-->

clothing_store/shop/templates/shop/categories_in_header.html
<div class="container2">
    <div class="header-first1">
        <ul class="header-menu">
            {% for cat in categories %}
            {% if category_selected == cat.id %}
            {{cat.id}}
            {{category_selected}}
            <li><a href="#">{{ cat.name }}</a></li>
            {% else %}
            <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

<!--<div class="container2">-->
<!--    <div class="header-first1">-->
<!--        <ul class="header-menu">-->
<!--            <li><a href="http://127.0.0.1:8000/category/t-shirts/#">Футболки</a></li>-->
<!--            <li><a href="http://127.0.0.1:8000/category/sweatshirts/">Свитшоты/худи</a></li>-->
<!--            <li><a href="http://127.0.0.1:8000/category/pants-shorts/">Штаны/шорты</a></li>-->
<!--            <li><a href="http://127.0.0.1:8000/category/hats/">Шапки</a></li>-->
<!--            <li><a href="http://127.0.0.1:8000/category/bags/">Рюкзаки/сумки</a></li>-->
<!--        </ul>-->
<!--    </div>-->

<!--</div>-->

clothing_store/shop/templates/shop/my_orders.html
{% extends 'shop/base.html' %}
{% load currency_cart %}
{% block content %}

<selection class="profile_page app-page">
    <h1 class="account-page-title">Мой аккаунт</h1>

    <div class="account-page-content">
        <div class="account-page-side">
            <ul class="account-page-menu">
                <li class="account-page-menu-item hoverable">
                    <a href="/account">Личные данные</a>
                </li>
                <li class="account-page-menu-item hoverable active">
                    <a href="#">— Мои заказы</a>
                </li>
            </ul>
            <a href="{% url 'logout' %}" >
                <button type="submit" class="account-page-logout hoverable">
                    <span>Выйти из аккаунта</span>
                </button>
            </a>
        </div>
        <div class="account-page-page">
            <div class="account__orders">
                <div class="account__orders-title">История заказов</div>
                <div class="account__orders-list">
                    <div class="account__order-container">
                        {% for order in orders %}
                        <div class="account__order">
                            <div class="account__order-item account__order-date">
                                <span class="account__order-label">Дата заказа:</span>
                                <span class="account__order-value">{{ order.date_create }}</span>
                                <br><span class="account__order-label">Дата обновления:</span>
                                <span class="account__order-value">{{ order.date_update }}</span>
                                <br><span class="account__order-label">Состояние заказа</span>
                                <span class="account__order-value">{{ order.status }}</span>

                            </div>
                            <div class="account__order-item account__order-details">
                                <span class="account__order-label">Детали заказа:</span>
                                <span class="account__order-value">Номер заказа: {{ order.pk }}</span>
                                <br><span class="account__order-label">Товары:</span>
                                {% for link in order.linkinordersanditems_set.all %}
                                <span class="account__order-value">{{ link.item }}</span>
                                <span class="account__order-value">Количество: {{ link.quantity }}</span>
                                <span class="account__order-value">Размер: {{ link.size }}</span>
                                <span class="account__order-value">Цена: {{ link.item.price|currency_cart:user.currency }} {{ user.currency }}</span>
                                    <br>
                                {% endfor %}
                                <br><span class="account__order-label">Итоговая стоимость</span>
                                <span class="account__order-value">{{ order.total_price|currency_cart:user.currency }} {{ user.currency }}</span>

                            </div>
                            <div class="account__order-item account__order-delivery">

                                <span class="account__order-value">&nbsp</span>
                                <span class="account__order-label">Адрес доставки:</span>
                                <span class="account__order-value">{{ order.country }}<br>{{ order.region }}<br>{{ order.city }}<br>{{ order.address }}<br>{{ order.mail_index }}</span>
                                <span class="account__order-value">&nbsp</span>
                                <span class="account__order-label">Заказчик:</span>
                                <span class="account__order-value">{{ order.first_name }} {{ order.last_name }} {{ order.middle_name }}</span>
                                <span class="account__order-value">&nbsp</span>
                                <span class="account__order-label">Контакты:</span>
                                <span class="account__order-value">{{ order.email }}</span>
                                <span class="account__order-value">{{ order.phone }}</span><br>
                                <span class="account__order-label">Промокод:</span>
                                <span class="account__order-value">-</span>
                            </div>
                            {% if order.status == "Не оплачен" %}
                            <a href="/order/{{ order.payment_code }}__{{ order.total_price }}" class="nothing"><button class="check-payment-button">Проверить оплату</button></a>
                            {% endif %}
                        </div>

                        {% endfor %}
                    </div>
                </div>
                {% if not orders %}
                <div class="account__orders-empty active">История заказов пуста</div>
                {% endif %}
            </div>
        </div>
    </div>
</selection>
{% endblock %}